CREATE DATABASE VEGANOLOGO;
USE VEGANOLOGO;

CREATE TABLE IF NOT EXISTS VEG_USUARIO(

    USU_ID INT NOT NULL AUTO_INCREMENT,
    USU_NOME VARCHAR(45) NOT NULL,
    USU_EMAIL VARCHAR(45) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(8) NOT NULL,
    CONSTRAINT USU_PK PRIMARY KEY (USU_ID) 

);

CREATE TABLE IF NOT EXISTS VEG_RECEITA(


    REC_ID INT NOT NULL AUTO_INCREMENT,
    REC_USU_ID INT NOT NULL,
    REC_NOME VARCHAR(20) NOT NULL UNIQUE,
    REC_INGREDIENTES TEXT NOT NULL,
    REC_PREPARO TEXT NOT NULL,
   /*REC_FOTO VARBINARY(max) NOT NULL,*/
    REC_UTENSILHOS TEXT NOT NULL,
    CONSTRAINT REC_PK PRIMARY KEY (REC_ID),
    CONSTRAINT REC_USU_FK FOREIGN KEY (REC_USU_ID) REFERENCES VEG_USUARIO (USU_ID)  


);

/* Adicionar usuario e receitas fakes para aparecer mais opções, como a lista de receitas etc... */
